// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afnythdjlarqfxyethyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmbnl0aGRqbGFycWZ4eWV0aHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjExODksImV4cCI6MjA2OTQzNzE4OX0.O0yS5IBKBlj1WwYRsWO4pP8Sm8RxMxdRzXCFe0xt55Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});